/* eslint-disable linebreak-style */
const DONE_CODE = 200;
const CREATE_CODE = 201;
const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN_CODE = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT_CODE = 409;
const GLOBAL_ERROR_SERVER = 500;

module.exports = {
  DONE_CODE,
  CREATE_CODE,
  BAD_REQUEST_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  CONFLICT_CODE,
  GLOBAL_ERROR_SERVER,
};
